# Generated by Django 5.2 on 2025-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puestomodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
    ]
