# Generated by Django 5.2 on 2025-04-29 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('incidencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NomiaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('fecha_generacion', models.DateField(help_text='Fecha en la que se generó la nómina', verbose_name='Fecha de Generación')),
                ('total_percepciones', models.DecimalField(decimal_places=2, help_text='Total de percepciones del empleado', max_digits=10, verbose_name='Total de Percepciones')),
                ('total_deducciones', models.DecimalField(decimal_places=2, help_text='Total de deducciones del empleado', max_digits=10, verbose_name='Total de Deducciones')),
                ('total_neto', models.DecimalField(decimal_places=2, help_text='Total neto a pagar al empleado', max_digits=10, verbose_name='Total Neto')),
                ('fecha_pago', models.DateField(blank=True, help_text='Fecha en la que se realizó el pago', null=True, verbose_name='Fecha de Pago')),
                ('fecha_inicio', models.DateField(blank=True, help_text='Fecha de inicio del periodo de pago', null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Fecha de fin del periodo de pago', null=True, verbose_name='Fecha de Fin')),
                ('estado_nomina', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('GENERADA', 'Generada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Nómina')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nomina_empleado', to='empleado.empleadomodel', verbose_name='Empleado')),
                ('incidencias', models.ManyToManyField(related_name='nomina_incidencias', to='incidencia.incidenciasempleados', verbose_name='Incidencias')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'db_table': 'nomina',
            },
        ),
    ]
