# Generated by Django 5.2 on 2025-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomiamodel',
            name='total_deducciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de deducciones del empleado', max_digits=10, null=True, verbose_name='Total de Deducciones'),
        ),
        migrations.AlterField(
            model_name='nomiamodel',
            name='total_neto',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total neto a pagar al empleado', max_digits=10, null=True, verbose_name='Total Neto'),
        ),
        migrations.AlterField(
            model_name='nomiamodel',
            name='total_percepciones',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de percepciones del empleado', max_digits=10, null=True, verbose_name='Total de Percepciones'),
        ),
    ]
