# Generated by Django 5.2 on 2025-04-25 18:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleadomodel_status_postulantemodel_status'),
        ('incidencia', '0003_incidenciasempleados_monto_and_more'),
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nomia',
            new_name='NomiaModel',
        ),
    ]
