# Generated by Django 5.2 on 2025-05-23 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
        ('nomina', '0002_alter_nomiamodel_total_deducciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomiamodel',
            name='incidencias',
        ),
        migrations.AddField(
            model_name='nomiamodel',
            name='incidencias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nomina_incidencias', to='incidencia.incidenciasempleados', verbose_name='Incidencias'),
        ),
    ]
