# Generated by Django 5.2 on 2025-05-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
        ('nomina', '0003_remove_nomiamodel_incidencias_nomiamodel_incidencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomiamodel',
            name='incidencias',
        ),
        migrations.AddField(
            model_name='nomiamodel',
            name='incidencias',
            field=models.ManyToManyField(blank=True, null=True, related_name='nomina_incidencias', to='incidencia.incidenciasempleados', verbose_name='Incidencias'),
        ),
    ]
