# Generated by Django 5.2 on 2025-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_remove_nomiamodel_incidencias_nomiamodel_incidencias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomiamodel',
            name='fecha_generacion',
            field=models.DateField(auto_now_add=True, help_text='Fecha en la que se generó la nómina', verbose_name='Fecha de Generación'),
        ),
    ]
