# Generated by Django 5.2 on 2025-06-19 20:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_alter_postulantemodel_contrato_and_more'),
        ('incidencia', '0001_initial'),
        ('nomina', '0005_alter_nomiamodel_fecha_generacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NomiaModel',
            new_name='NominaModel',
        ),
    ]
