# Generated by Django 5.2 on 2025-04-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('empleado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('efecto', models.CharField(choices=[('ADD', 'Percepción (suma)'), ('SUB', 'Deducción (resta)'), ('NONE', 'Sin efecto económico'), ('ACCUM', 'Acumulativa')], default='NONE', max_length=5, verbose_name='Efecto en nómina')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Incidencias',
                'verbose_name_plural': 'Categorías de Incidencias',
                'db_table': 'categoria_incidencias',
            },
        ),
        migrations.CreateModel(
            name='FormulaIncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('formula_detalle', models.TextField(blank=True, null=True, verbose_name='Detalle de la Fórmula')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fórmula de Incidencias',
                'verbose_name_plural': 'Fórmulas de Incidencias',
                'db_table': 'formulas_incidencias',
            },
        ),
        migrations.CreateModel(
            name='TipoIncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_incidencia', to='incidencia.categoriaincidenciasmodel', verbose_name='Categoría de Incidencia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_incidencia', to='incidencia.formulaincidenciasmodel', verbose_name='Fórmula de Incidencia')),
                ('referencia_monto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_incidencia', to='contrato.contratomodel', verbose_name='Referencia de Monto')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencias',
                'db_table': 'tipo_incidencias',
            },
        ),
        migrations.CreateModel(
            name='IncidenciasEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField(verbose_name='Fecha de la Incidencia')),
                ('estado_incidencia', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Incidencia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_empleado', to='empleado.empleadomodel', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_tipo', to='incidencia.tipoincidenciasmodel', verbose_name='Tipo de Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia de Empleado',
                'verbose_name_plural': 'Incidencias de Empleados',
                'db_table': 'incidencias_empleados',
            },
        ),
        migrations.CreateModel(
            name='TiposFormulasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(blank=True, help_text='Código único para identificar el tipo de fórmula', max_length=3, null=True, unique=True, verbose_name='Código')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Fórmula',
                'verbose_name_plural': 'Tipos de Fórmulas',
                'db_table': 'tipo_formula_incidencias',
            },
        ),
        migrations.AddField(
            model_name='formulaincidenciasmodel',
            name='codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formula', to='incidencia.tiposformulasmodel', verbose_name='Tipo de Fórmula'),
        ),
    ]
