# Generated by Django 5.2 on 2025-04-29 17:16

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaIncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código')),
                ('efecto', models.CharField(choices=[('ADD', 'Percepción (suma)'), ('SUB', 'Deducción (resta)'), ('NONE', 'Sin efecto económico'), ('ACCUM', 'Acumulativa')], default='NONE', max_length=5, verbose_name='Efecto en nómina')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Categoría de Incidencias',
                'verbose_name_plural': 'Categorías de Incidencias',
                'db_table': 'categoria_incidencias',
            },
        ),
        migrations.CreateModel(
            name='TipoIncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipo_incidencia', to='incidencia.categoriaincidenciasmodel', verbose_name='Categoría de Incidencia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Incidencia',
                'verbose_name_plural': 'Tipos de Incidencias',
                'db_table': 'tipo_incidencias',
            },
        ),
        migrations.CreateModel(
            name='IncidenciasEmpleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('fecha', models.DateField(verbose_name='Fecha de la Incidencia')),
                ('estado_incidencia', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=10, verbose_name='Estado de la Incidencia')),
                ('observaciones', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Observaciones')),
                ('dif_puesto', models.BooleanField(default=False, help_text='Indica si la incidencia es para un puesto diferente al habitual', verbose_name='Diferente puesto de trabajo')),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la Incidencia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_empleado', to='empleado.empleadomodel', verbose_name='Empleado')),
                ('empleado_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_empleado_obj', to='empleado.empleadomodel', verbose_name='Empleado Objetivo')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_tipo', to='incidencia.tipoincidenciasmodel', verbose_name='Tipo de Incidencia')),
            ],
            options={
                'verbose_name': 'Incidencia de Empleado',
                'verbose_name_plural': 'Incidencias de Empleados',
                'db_table': 'incidencias_empleados',
            },
        ),
    ]
