# Generated by Django 5.2 on 2025-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriaincidenciasmodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='formulaincidenciasmodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='incidenciasempleados',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tipoincidenciasmodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='tiposformulasmodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
    ]
