# Generated by Django 5.2 on 2025-06-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidenciasempleados',
            options={'permissions': [('editar_incidencias', 'Puede editar el concepto de incidencias')], 'verbose_name': 'Incidencia de Empleado', 'verbose_name_plural': 'Incidencias de Empleados'},
        ),
    ]
