# Generated by Django 5.2 on 2025-04-18 17:42

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0009_alter_postulantemodel_table'),
        ('incidencia', '0001_initial'),
        ('puesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenciasEmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incident_date', models.DateField(verbose_name='Fecha de incidencia')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('hours', models.DecimalField(decimal_places=2, default=0, help_text='Número de horas para incidencias por tiempo', max_digits=5, verbose_name='Horas')),
                ('details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Detalles')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto calculado o manual de la incidencia', max_digits=12, null=True, verbose_name='Monto')),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('AP', 'Aprobada'), ('RE', 'Rechazada'), ('CA', 'Cancelada'), ('PR', 'Procesada')], default='PE', max_length=2, verbose_name='Estado')),
                ('is_generated', models.BooleanField(default=False, help_text='Indica si esta incidencia fue generada automáticamente por acumulación', verbose_name='Generada automáticamente')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación')),
                ('document', models.FileField(blank=True, null=True, upload_to='incident_documents/', verbose_name='Documento de soporte')),
                ('processed_in_payroll', models.BooleanField(default=False, verbose_name='Procesado en nómina')),
                ('payroll_period', models.CharField(blank=True, max_length=20, null=True, verbose_name='Periodo de nómina')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_incidents', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='empleado.empleadomodel', verbose_name='Empleado')),
                ('parent_incident', models.ForeignKey(blank=True, help_text='Para incidencias generadas automáticamente por acumulación', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_incidents', to='incidencia.incidenciasempleadomodel', verbose_name='Incidencia origen')),
                ('puesto_objetivo', models.ForeignKey(blank=True, help_text='Para incidencias que implican cambio temporal de puesto', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_temporales', to='puesto.puestomodel', verbose_name='Puesto objetivo')),
                ('tipo_incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_empleado', to='incidencia.tipoincidenciamodel', verbose_name='Tipo de incidencia')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidencia de empleado',
                'verbose_name_plural': 'Incidencias de empleados',
                'db_table': 'employee_incidents',
            },
        ),
    ]
