# Generated by Django 5.2 on 2025-04-25 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleadomodel_status_postulantemodel_status'),
        ('incidencia', '0002_alter_incidenciasempleados_empleado_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidenciasempleados',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto de la Incidencia'),
        ),
        migrations.AlterField(
            model_name='incidenciasempleados',
            name='empleado_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_empleado_obj', to='empleado.empleadomodel', verbose_name='Empleado Objetivo'),
        ),
    ]
