# Generated by Django 5.2 on 2025-06-25 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencia', '0002_alter_incidenciasempleados_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionIncidenciasModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('tipo_asistencia', models.CharField(choices=[('ASISTENCIA', 'Asistencia'), ('FALTA', 'Falta'), ('TARDANZA', 'Tardanza')], default='ASISTENCIA', max_length=10, verbose_name='Tipo de Asistencia')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('incidencia', models.ForeignKey(help_text='Tipo de Incidencia', on_delete=django.db.models.deletion.PROTECT, to='incidencia.tipoincidenciasmodel', verbose_name='Tipo de Incidencia')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Incidencias',
                'verbose_name_plural': 'Configuraciones de Incidencias',
                'db_table': 'configuracion_incidencias',
            },
        ),
    ]
