# Generated by Django 5.2 on 2025-06-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0019_alter_contratomodel_tipo_contrato'),
        ('incidencia', '0003_configuracionincidenciasmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidenciasempleados',
            name='empleado_obj',
        ),
        migrations.AddField(
            model_name='incidenciasempleados',
            name='contrato_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias_contrato_obj', to='contrato.contratomodel', verbose_name='Contrato Objetivo'),
        ),
    ]
