# Generated by Django 5.2 on 2025-04-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SucursalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100)),
                ('calle', models.CharField(blank=True, help_text='Calle de la empresa', max_length=255, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, help_text='Número de la calle de la empresa', max_length=10, null=True, verbose_name='Número')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad de la empresa', max_length=255, null=True, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal de la empresa', max_length=10, null=True, verbose_name='Código Postal')),
                ('provincia', models.CharField(blank=True, help_text='Provincia de la empresa', max_length=255, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(blank=True, help_text='País de la empresa', max_length=255, null=True, verbose_name='País')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de la empresa', max_length=20, null=True, verbose_name='Teléfono')),
                ('fax', models.CharField(blank=True, help_text='Fax de la empresa', max_length=20, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, help_text='Email de la empresa', max_length=255, null=True, verbose_name='Email')),
                ('web', models.URLField(blank=True, help_text='Página web de la empresa', max_length=255, null=True, verbose_name='Web')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='empresa.empresamodel')),
                ('encargado', models.ForeignKey(blank=True, help_text='Encargado de la sucursal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_encargado', to=settings.AUTH_USER_MODEL, verbose_name='Encargado')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
            },
        ),
    ]
