# Generated by Django 5.2 on 2025-04-07 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursalmodel',
            name='encargado',
            field=models.ForeignKey(blank=True, help_text='Encargado de la sucursal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_encargado', to=settings.AUTH_USER_MODEL, verbose_name='Encargado'),
        ),
    ]
