# Generated by Django 5.2 on 2025-04-21 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('razon_social', models.CharField(help_text='Razón social de la empresa', max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, help_text='Nombre comercial de la empresa', max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('calle', models.CharField(blank=True, help_text='Calle de la empresa', max_length=255, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, help_text='Número de la calle de la empresa', max_length=10, null=True, verbose_name='Número')),
                ('ciudad', models.CharField(blank=True, help_text='Ciudad de la empresa', max_length=255, null=True, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, help_text='Código postal de la empresa', max_length=10, null=True, verbose_name='Código Postal')),
                ('provincia', models.CharField(blank=True, help_text='Provincia de la empresa', max_length=255, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(blank=True, help_text='País de la empresa', max_length=255, null=True, verbose_name='País')),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de la empresa', max_length=20, null=True, verbose_name='Teléfono')),
                ('fax', models.CharField(blank=True, help_text='Fax de la empresa', max_length=20, null=True, verbose_name='Fax')),
                ('email', models.EmailField(blank=True, help_text='Email de la empresa', max_length=255, null=True, verbose_name='Email')),
                ('web', models.URLField(blank=True, help_text='Página web de la empresa', max_length=255, null=True, verbose_name='Web')),
                ('rfc', models.CharField(blank=True, help_text='RFC de la empresa', max_length=13, null=True, verbose_name='RFC')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresas',
            },
        ),
    ]
