# Generated by Django 5.2 on 2025-04-29 17:32

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contrato', '0001_initial'),
        ('puesto', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostulanteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('ciudad', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('provincia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia')),
                ('pais', models.CharField(blank=True, max_length=255, null=True, verbose_name='País')),
                ('notas', tinymce.models.HTMLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_contrato', to='contrato.contratomodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_puesto', to='puesto.puestomodel')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Postulante',
                'verbose_name_plural': 'Postulantes',
                'db_table': 'postulantes',
            },
        ),
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('notas', tinymce.models.HTMLField(blank=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_contrato', to='contrato.contratomodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_puesto', to='puesto.puestomodel')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_sucursal', to='sucursal.sucursalmodel')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_postulante', to='empleado.postulantemodel')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleados',
                'managed': True,
            },
        ),
    ]
