# Generated by Django 5.2 on 2025-04-08 19:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contratomodel_frecuencia_pago_and_more'),
        ('empleado', '0001_initial'),
        ('puesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Postulante',
            new_name='PostulanteModel',
        ),
        migrations.AlterModelOptions(
            name='postulantemodel',
            options={'verbose_name': 'Postulante', 'verbose_name_plural': 'Postulantes'},
        ),
        migrations.AlterModelTable(
            name='postulantemodel',
            table='empleado_postulante',
        ),
    ]
