# Generated by Django 5.2 on 2025-05-22 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contratomodel_tipo_contrato'),
        ('empleado', '0001_initial'),
        ('puesto', '0001_initial'),
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleadomodel',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_contrato', to='contrato.contratomodel'),
        ),
        migrations.AlterField(
            model_name='empleadomodel',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_puesto', to='puesto.puestomodel'),
        ),
        migrations.AlterField(
            model_name='empleadomodel',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_sucursal', to='sucursal.sucursalmodel'),
        ),
        migrations.AlterField(
            model_name='postulantemodel',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_contrato', to='contrato.contratomodel'),
        ),
        migrations.AlterField(
            model_name='postulantemodel',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_puesto', to='puesto.puestomodel'),
        ),
    ]
