# Generated by Django 5.2 on 2025-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_rename_postulante_postulantemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantemodel',
            name='calle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='postulantemodel',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='postulantemodel',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='postulantemodel',
            name='numero',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='postulantemodel',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='postulantemodel',
            name='provincia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Provincia'),
        ),
    ]
