# Generated by Django 5.2 on 2025-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleadomodel_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulantemodel',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
