# Generated by Django 5.2 on 2025-05-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_alter_postulantemodel_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadomodel',
            name='fecha_contratacion',
            field=models.DateField(blank=True, help_text='Fecha de contratación del empleado', null=True, verbose_name='Fecha de Contratación'),
        ),
    ]
