# Generated by Django 5.2 on 2025-04-14 18:46

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_alter_contratomodel_frecuencia_pago_and_more'),
        ('empleado', '0004_alter_postulantemodel_usuario'),
        ('puesto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postulantemodel',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aceptado'), ('R', 'Rechazado')], default='P', max_length=1),
        ),
        migrations.CreateModel(
            name='EmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notas', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_contrato', to='contrato.contratomodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('postulante', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_postulante', to='empleado.postulantemodel')),
                ('puesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_puesto', to='puesto.puestomodel')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
