# Generated by Django 5.2 on 2025-04-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0005_postulantemodel_estado_empleadomodel'),
        ('sucursal', '0002_sucursalmodel_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadomodel',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_sucursal', to='sucursal.sucursalmodel'),
        ),
    ]
