# Generated by Django 5.2 on 2025-04-15 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0007_alter_empleadomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulantemodel',
            table='postulante',
        ),
    ]
