# Generated by Django 5.2 on 2025-04-15 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0008_alter_postulantemodel_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postulantemodel',
            table='postulantes',
        ),
    ]
