# Generated by Django 5.2 on 2025-04-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contratomodel',
            options={'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('S', 'Semanal'), ('A', 'Anual'), ('D', 'Diario'), ('B', 'Quincenal'), ('M', 'Mensual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('D', 'Definido'), ('P', 'Indefinido'), ('T', 'Temporal'), ('S', 'Servicio')], max_length=1),
        ),
        migrations.AlterModelTable(
            name='contratomodel',
            table='contratos',
        ),
    ]
