# Generated by Django 5.2 on 2025-05-22 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('P', 'Indefinido'), ('D', 'Definido'), ('S', 'Servicio')], max_length=1),
        ),
    ]
