# Generated by Django 5.2 on 2025-04-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomodel',
            name='status',
            field=models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('D', 'Definido'), ('P', 'Indefinido'), ('S', 'Servicio')], max_length=1),
        ),
    ]
