# Generated by Django 5.2 on 2025-05-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('S', 'Servicio'), ('D', 'Definido'), ('T', 'Temporal'), ('P', 'Indefinido')], max_length=1),
        ),
    ]
