# Generated by Django 5.2 on 2025-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0002_alter_contratomodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('B', 'Quincenal'), ('M', 'Mensual'), ('D', 'Diario'), ('A', 'Anual'), ('S', 'Semanal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('P', 'Indefinido'), ('S', 'Servicio'), ('T', 'Temporal'), ('D', 'Definido')], max_length=1),
        ),
    ]
