# Generated by Django 5.2 on 2025-05-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('D', 'Definido'), ('P', 'Indefinido'), ('T', 'Temporal'), ('S', 'Servicio')], max_length=1),
        ),
    ]
