# Generated by Django 5.2 on 2025-04-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomodel',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('A', 'Anual'), ('D', 'Diario'), ('B', 'Quincenal'), ('M', 'Mensual'), ('S', 'Semanal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('P', 'Indefinido'), ('T', 'Temporal'), ('D', 'Definido'), ('S', 'Servicio')], max_length=1),
        ),
    ]
