# Generated by Django 5.2 on 2025-04-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0003_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('D', 'Definido'), ('S', 'Servicio'), ('P', 'Indefinido')], max_length=1),
        ),
    ]
