# Generated by Django 5.2 on 2025-04-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0004_contratomodel_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('D', 'Diario'), ('A', 'Anual'), ('Q', 'Quincenal'), ('S', 'Semanal'), ('M', 'Mensual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('S', 'Servicio'), ('P', 'Indefinido'), ('D', 'Definido')], max_length=1),
        ),
    ]
