# Generated by Django 5.2 on 2025-05-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Indefinido', 'Indefinido'), ('Temporal', 'Temporal'), ('Definido', 'Definido'), ('Servicio', 'Servicio')], max_length=20),
        ),
    ]
