# Generated by Django 5.2 on 2025-04-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0005_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('A', 'Anual'), ('S', 'Semanal'), ('D', 'Diario'), ('Q', 'Quincenal'), ('M', 'Mensual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('S', 'Servicio'), ('D', 'Definido'), ('P', 'Indefinido')], max_length=1),
        ),
    ]
