# Generated by Django 5.2 on 2025-04-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0006_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('A', 'Anual'), ('D', 'Diario'), ('Q', 'Quincenal'), ('S', 'Semanal'), ('M', 'Mensual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('P', 'Indefinido'), ('S', 'Servicio'), ('T', 'Temporal'), ('D', 'Definido')], max_length=1),
        ),
    ]
