# Generated by Django 5.2 on 2025-05-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0006_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Temporal', 'Temporal'), ('Servicio', 'Servicio'), ('Indefinido', 'Indefinido'), ('Definido', 'Definido')], max_length=20),
        ),
    ]
