# Generated by Django 5.2 on 2025-04-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0006_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('P', 'Indefinido'), ('S', 'Servicio'), ('D', 'Definido')], max_length=1),
        ),
    ]
