# Generated by Django 5.2 on 2025-04-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('P', 'Indefinido'), ('D', 'Definido'), ('S', 'Servicio'), ('T', 'Temporal')], max_length=1),
        ),
    ]
