# Generated by Django 5.2 on 2025-04-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0007_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('D', 'Diario'), ('Q', 'Quincenal'), ('M', 'Mensual'), ('A', 'Anual'), ('S', 'Semanal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('S', 'Servicio'), ('P', 'Indefinido'), ('T', 'Temporal'), ('D', 'Definido')], max_length=1),
        ),
    ]
