# Generated by Django 5.2 on 2025-04-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0008_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('M', 'Mensual'), ('Q', 'Quincenal'), ('A', 'Anual'), ('D', 'Diario'), ('S', 'Semanal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('T', 'Temporal'), ('P', 'Indefinido'), ('S', 'Servicio'), ('D', 'Definido')], max_length=1),
        ),
    ]
