# Generated by Django 5.2 on 2025-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0009_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Definido', 'Definido'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal')], max_length=20),
        ),
    ]
