# Generated by Django 5.2 on 2025-04-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0009_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('M', 'Mensual'), ('A', 'Anual'), ('D', 'Diario'), ('S', 'Semanal'), ('Q', 'Quincenal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('P', 'Indefinido'), ('D', 'Definido'), ('S', 'Servicio'), ('T', 'Temporal')], max_length=1),
        ),
    ]
