# Generated by Django 5.2 on 2025-04-15 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0010_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('M', 'Mensual'), ('Q', 'Quincenal'), ('D', 'Diario'), ('A', 'Anual'), ('S', 'Semanal')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('D', 'Definido'), ('P', 'Indefinido'), ('S', 'Servicio'), ('T', 'Temporal')], max_length=1),
        ),
    ]
