# Generated by Django 5.2 on 2025-06-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0011_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Servicio', 'Servicio'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal'), ('Definido', 'Definido')], max_length=20),
        ),
    ]
