# Generated by Django 5.2 on 2025-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0012_alter_contratomodel_frecuencia_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratomodel',
            name='horas_trabajo',
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='frecuencia_pago',
            field=models.CharField(choices=[('S', 'Semanal'), ('M', 'Mensual'), ('D', 'Diario'), ('Q', 'Quincenal'), ('A', 'Anual')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('D', 'Definido'), ('T', 'Temporal'), ('P', 'Indefinido'), ('S', 'Servicio')], max_length=1),
        ),
    ]
