# Generated by Django 5.2 on 2025-06-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0012_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Definido', 'Definido'), ('Servicio', 'Servicio'), ('Indefinido', 'Indefinido'), ('Temporal', 'Temporal')], max_length=20),
        ),
    ]
