# Generated by Django 5.2 on 2025-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0013_remove_contratomodel_horas_trabajo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratomodel',
            name='frecuencia_pago',
        ),
        migrations.AddField(
            model_name='contratomodel',
            name='horas_trabajo',
            field=models.IntegerField(default=0, help_text='Horas de trabajo diarias'),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Salario diario', max_digits=10),
        ),
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('D', 'Definido'), ('S', 'Servicio'), ('P', 'Indefinido'), ('T', 'Temporal')], max_length=1),
        ),
    ]
