# Generated by Django 5.2 on 2025-06-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0013_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Temporal', 'Temporal'), ('Servicio', 'Servicio'), ('Definido', 'Definido'), ('Indefinido', 'Indefinido')], max_length=20),
        ),
    ]
