# Generated by Django 5.2 on 2025-06-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0014_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Temporal', 'Temporal'), ('Definido', 'Definido'), ('Indefinido', 'Indefinido'), ('Servicio', 'Servicio')], max_length=20),
        ),
    ]
