# Generated by Django 5.2 on 2025-06-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0016_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Temporal', 'Temporal'), ('Indefinido', 'Indefinido'), ('Servicio', 'Servicio'), ('Definido', 'Definido')], max_length=20),
        ),
    ]
