# Generated by Django 5.2 on 2025-06-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0017_alter_contratomodel_tipo_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratomodel',
            name='personalizado',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si el contrato es personalizado', null=True, verbose_name='Contrato Personalizado'),
        ),
    ]
