# Generated by Django 5.2 on 2025-06-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrato', '0018_contratomodel_personalizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratomodel',
            name='tipo_contrato',
            field=models.CharField(choices=[('Definido', 'Definido'), ('Temporal', 'Temporal'), ('Indefinido', 'Indefinido'), ('Servicio', 'Servicio')], max_length=20),
        ),
    ]
