# Generated by Django 5.2 on 2025-04-29 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleado', '0001_initial'),
        ('sucursal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SemanaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semana_sucursal', to='sucursal.sucursalmodel', verbose_name='Sucursal')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Semana',
                'verbose_name_plural': 'Semanas',
                'db_table': 'semana',
            },
        ),
        migrations.CreateModel(
            name='TurnosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='turno_sucursal', to='sucursal.sucursalmodel', verbose_name='Sucursal')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turno',
            },
        ),
        migrations.CreateModel(
            name='ProgramacionDiariaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('dia', models.DateField(help_text='Día de la programación', verbose_name='Día')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='horario.semanamodel', verbose_name='Semana')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='horario.turnosmodel', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Programación Diaria',
                'verbose_name_plural': 'Programaciones Diarias',
                'db_table': 'programacion_diaria',
                'unique_together': {('semana', 'dia', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_horario', to='empleado.empleadomodel', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horario.programaciondiariamodel', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'Asignación de Empleado',
                'verbose_name_plural': 'Asignaciones de Empleados',
                'db_table': 'asignacion_empleado',
                'unique_together': {('programacion', 'empleado')},
            },
        ),
    ]
