# Generated by Django 5.2 on 2025-04-25 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_empleadomodel_status_postulantemodel_status'),
        ('horario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramacionDiariaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('dia', models.DateField(help_text='Día de la programación', verbose_name='Día')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='horario.semanamodel', verbose_name='Semana')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programaciones', to='horario.turnosmodel', verbose_name='Turno')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programación Diaria',
                'verbose_name_plural': 'Programaciones Diarias',
                'db_table': 'programacion_diaria',
                'unique_together': {('semana', 'dia', 'turno')},
            },
        ),
        migrations.CreateModel(
            name='AsignacionEmpleadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True, help_text='Estado del registro', verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_horario', to='empleado.empleadomodel', verbose_name='Empleado')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('programacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='horario.programaciondiariamodel', verbose_name='Programación')),
            ],
            options={
                'verbose_name': 'Asignación de Empleado',
                'verbose_name_plural': 'Asignaciones de Empleados',
                'db_table': 'asignacion_empleado',
                'unique_together': {('programacion', 'empleado')},
            },
        ),
        migrations.DeleteModel(
            name='HorarioModel',
        ),
    ]
