# Generated by Django 5.2 on 2025-06-25 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacionempleadomodel',
            name='observaciones',
        ),
    ]
